Test/database
AndreyCorpse280990/wildberries pull request #3
Opened 2022-03-23 15:19 UTC by AndreyCorpse280990

2022-03-25 05:47 UTC, AndreyCorpse280990 commented
Нужна помощь с selenium_similar, в строке 49 не могу убрать пробел между цифрами. .replace() 2 раза не работает) ([price.get_text().strip().replace("₽", '').replace(" ", '') for price in find_price]) - так пробовал.

2022-03-28 09:50 UTC, ermolushka requested changes
Нужно исправить пару мест

2022-03-28 09:50 UTC, ermolushka commented on webapp/saving_to_database.py
> +    url = db.Column(db.String, db.ForeignKey('item.url'), nullable=False)
Нет, ты должен связать таблицы через item_id. То есть в таблице ItemPrice у тебя должно быть id, price, item (item будет foreign key). Тут ты связываешь по url, который еще и не является primary_key - это будет медленно и некорректно.

2022-03-28 09:53 UTC, ermolushka commented
> Нужна помощь с selenium_similar, в строке 49 не могу убрать пробел между цифрами. .replace() 2 раза не работает) ([price.get_text().strip().replace("₽", '').replace(" ", '') for price in find_price]) - так пробовал. Так же посмотреть saving_to_database, тестово сделал, для понятия логики фреймворка. ![124](https://user-images.githubusercontent.com/99309269/160062248-702b3cad-218a-4271-8577-14d88012b5ab.jpg) В базе вот как выглядит. Так же нужна помощь с хешированием пароля. https://variable-scope.com/posts/storing-and-verifying-passwords-with-sqlalchemy нашёл вот такой вариант при помощи bcrypt ps. "href" не вытащил, через select не получается, нужно через find\get вытащить попробовать, но пока не вникал.

если решать форматирование цены в лоб, то можно так

```
price = ""
parsed_price = "20 333р"

for i in parsed_price:
   if i.isdigit():
      price += i
```

2022-03-31 19:48 UTC, ermolushka commented on webapp/saving_to_database.py
> +    item = db.Column(db.String(200), nullable=False)
Зачем тут item? У нас же есть item_id

2022-03-31 19:48 UTC, ermolushka commented on webapp/selenium_similar.py
> +                print(div.find('a')['href'])
Нужно их возвращать так же, как и остальные, третьим массивом и проверять, что длины массивов равны, что парсинг не полетел

2022-04-05 10:50 UTC, ermolushka approved these changes

2022-04-05 11:08 UTC, merged